### PR TITLE
LT-slides

### PR DESCRIPTION
**Pull request by harshit-jain52**
- [x] 2021
- [x] 2022
- [x] 2023

### CODE REVIEW

**Comment by keshavpj1711** [comment]
We will only be updating the slide links for 2021, 22 and 23

**Comment by harshit-jain52** [comment]
> We will only be updating the slide links for 2021, 22 and 23

Not 2020?

**Comment by keshavpj1711** [comment]
> > We will only be updating the slide links for 2021, 22 and 23
> 
> Not 2020?

Since we don't have the ppt links for 2020

**Review by harshkhandeparkar — APPROVED** [review]

**Comment by harshkhandeparkar** [comment]
Thanks @harshit-jain52 @keshavpj1711! :rocket:

**Pull request merged**
